# Generated by Django 4.1.13 on 2024-02-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_delete_problem_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_file', models.FileField(upload_to='programingquestions')),
                ('testcases', models.FileField(upload_to='testcases')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramingQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.FileField(upload_to='usercodes')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.programingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
