# Generated by Django 5.0.1 on 2024-02-05 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_submission_delete_programingquestionattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="testcase",
        ),
    ]
