# Generated by Django 5.0.1 on 2024-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0007_remove_submission_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="programingquestion",
            name="title",
            field=models.CharField(default="Factorial Problem", max_length=250),
            preserve_default=False,
        ),
    ]
