# Generated by Django 5.0.1 on 2024-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0010_programingquestion_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="programingquestion",
            name="solution_snippet",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
