# Generated by Django 5.0.1 on 2024-02-06 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0011_programingquestion_solution_snippet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="is_correct",
            new_name="is_submitted",
        ),
    ]
