# Generated by Django 5.0.1 on 2024-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0012_rename_is_correct_submission_is_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
