# Generated by Django 5.0.1 on 2024-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_remove_quizattempt_is_submitted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
